In [1]:
#numpy
'''What is NumPy?
NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.'''


'''Why Use NumPy?
In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working 
with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.'''


'''Why is NumPy Faster Than Lists?
NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate
them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

'''

'''Data Science: is a branch of computer science where we study how to store, use and analyze data for 
deriving information from it.'''

'''pip install numpy'''

'''type(): This built-in Python function tells us the type of the object passed to it. Like in above code it
shows that arr is numpy.ndarray type.'''



#single dimensional array

import numpy as np

n1 = np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [2]:
type(n1)

numpy.ndarray

In [3]:
#multi dimensional array
import numpy as np
n2 = np.array([[10,20,30,40],[40,30,20,10]])
n2

array([[10, 20, 30, 40],
       [40, 30, 20, 10]])

In [4]:
#initializing numpy array with zeros    
#zeros methods
import numpy as np
n3 = np.zeros((1,2))   #note 1 is row and 2 is coluam 
n3

array([[0., 0.]])

In [5]:
import numpy as np
n4 = np.zeros((5,5))  #note 5 is row and 5 is coluam 
n4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
#initializing numpy array with same number

import numpy as np
n5 = np.full((2,2),10)
n5

array([[10, 10],
       [10, 10]])

In [7]:
import numpy as np
n6 = np.full((4,4),9)
n6

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

In [8]:
#initializing numpy array within a range
import numpy as np
n1=np.arange(10,20)  #in this ex 10 is starting range and 20 is ending range 
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [9]:
import numpy as np 
n2=np.arange(10,101,5)    #in this ex 10 is starting range and 101 is ending range , and 5 is increment
n2

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100])

In [10]:
#initializing numpy array with random numbers
import numpy as np
n1=np.random.randint(1,100,5)  #range start from 1 to 100 and 5 is find 5 random numbers
n1


array([64, 55, 53, 70, 29])

In [11]:
#checking the shape of numpy arrays

import numpy as np
n1=np.array([[1,2,3],[4,5,6]])
n1.shape




#in output the first number is row and second number is coluam 

(2, 3)

In [12]:
#change the shape of array 
n1.shape=(3,2)
n1.shape            #it change all the thing like row becomes column and column becomes raw

(3, 2)

In [13]:
n1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
#stacking methods are given below
# 1 vstack() method
# 2 hstack() method
# column_stack() method

In [15]:
# 1 vstack() method

import numpy as np
n1=np.array([10,20,30])
n2=np.array([40,50,60])    #vtsack method is use to change the verticle things 

np.vstack((n2,n1))


array([[40, 50, 60],
       [10, 20, 30]])

In [16]:
#2 hstack() method
    #htsack method is use to change the horizonta things 
    
import numpy as np 
n1=np.array([10,20,30])
n2=np.array([40,50,60])

np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

In [17]:
# column_stack() method
#this method is use change the raw in column 
    

n1=np.array([10,20,30])
n2=np.array([40,50,60])

np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [18]:
#intersection and difference
#intersect1d
#setdiff1d

import numpy as np
n1=np.array([10,20,30,40,50,60])
n2=np.array([50,60,70,80,90])

np.intersect1d(n1,n2)


array([50, 60])

In [19]:
import numpy as np 
n1=np.array([10,20,30,40,50,60,70])
n2=np.array([50,60,70,80,90])
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [20]:
n1=np.array([10,20,30,40,50,60,70])
n2=np.array([50,60,70,80,90])
np.setdiff1d(n2,n1)

array([80, 90])

In [21]:

#mathematics

#additiona array

In [22]:
import numpy as np   #this method is use to add all elements in array
n1=np.array([10,20])
n2=np.array([30,40])
np.sum([n1,n2])

100

In [23]:
import numpy as np
n1=np.array([10,20]) #this method is use to add all column in array
n2=np.array([30,40])
np.sum([n1,n2],axis=0)

array([40, 60])

In [24]:
import numpy as np
n1=np.array([10,20])
n2=np.array([30,40])
np.sum([n1,n2],axis=1)

array([30, 70])

In [25]:
n1=np.array([10,20])
n2=np.array([30,40])
np.sum([n2,n1],axis=1)

array([70, 30])

In [26]:
#scalar opretion 
#basic addition

import numpy as np
n1=np.array([10,20,30])
n1=n1+1
n1

array([11, 21, 31])

In [27]:
#basic subtraction 

import numpy as np
n1=np.array([10,20,30])
n1=n1-1
n1

array([ 9, 19, 29])

In [28]:
#basic multiplication
n1=np.array([10,20,30])
n1=n1*5
n1

array([ 50, 100, 150])

In [29]:
#basic division
n1=np.array([10,20,30])
n1=n1/5
n1

array([2., 4., 6.])

In [30]:
#for mean value
import numpy as np
n1=np.array([10,20,30,40])
np.mean(n1)

25.0

In [31]:
#for median
import numpy as np 
n1=np.array([10,20,30,40,50])
np.median(n1)

30.0

In [32]:
#for standard deviation 
import numpy as np
n1=np.array([1,4,5,37,399,30,40])
np.std(n1)

133.67093314309935

In [33]:
#matrix
import numpy as np
n1=np.array([[1,2,3],[4,5,6],[7,8,9]])
n2=np.array([[9,8,7],[6,5,4],[3,2,1]])

In [34]:
n1[0]

array([1, 2, 3])

In [35]:
n1[2]

array([7, 8, 9])

In [36]:
n1[1]

array([4, 5, 6])

In [37]:
n1[:,0]

array([1, 4, 7])

In [38]:
n1[:,1]

array([2, 5, 8])

In [39]:
n1.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [40]:
n1.dot(4)

array([[ 4,  8, 12],
       [16, 20, 24],
       [28, 32, 36]])

In [41]:
n1.dot(n2)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [42]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 2])

2nd element on 1st row:  3


In [43]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[1, 1])

2nd element on 1st row:  7


In [44]:
#Access the third element of the second array of the first array:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [45]:
'''Example Explained
arr[0, 1, 2] prints the value 6.

And this is why:

The first number represents the first dimension, which contains two arrays:
[[1, 2, 3], [4, 5, 6]]
and:
[[7, 8, 9], [10, 11, 12]]
Since we selected 0, we are left with the first array:
[[1, 2, 3], [4, 5, 6]]

The second number represents the second dimension, which also contains two arrays:
[1, 2, 3]
and:
[4, 5, 6]
Since we selected 1, we are left with the second array:
[4, 5, 6]

The third number represents the third dimension, which contains three values:
4
5
6
Since we selected 2, we end up with the third value:
6
'''

'Example Explained\narr[0, 1, 2] prints the value 6.\n\nAnd this is why:\n\nThe first number represents the first dimension, which contains two arrays:\n[[1, 2, 3], [4, 5, 6]]\nand:\n[[7, 8, 9], [10, 11, 12]]\nSince we selected 0, we are left with the first array:\n[[1, 2, 3], [4, 5, 6]]\n\nThe second number represents the second dimension, which also contains two arrays:\n[1, 2, 3]\nand:\n[4, 5, 6]\nSince we selected 1, we are left with the second array:\n[4, 5, 6]\n\nThe third number represents the third dimension, which contains three values:\n4\n5\n6\nSince we selected 2, we end up with the third value:\n6\n'

In [46]:
#Print the last element from the 2nd dim:

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])


Last element from 2nd dim:  10
